# eureka client
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
      
      
# actuator lib set
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info